config/routes.rb
Rails.application.routes.draw do
  root to: "landing_page#index"

  # Auth
  match "/auth/:provider/callback", to: "sessions#create", via: [:get, :post]
  get "/auth/failure", to: "sessions#failure"
  delete "sessions", to: "sessions#destroy"

  get "/dashboard", to: "dashboard#index"
  resources :time_entries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user
  validates_presence_of :user_id, :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_from_hash(hash)
    find_by_provider_and_uid(hash["provider"], hash["uid"])
  end

  def self.create_from_hash(hash, user = nil)
    user ||= User.from_omniauth!(hash)
    Authorization.find_or_create_by(
      user: user,
      uid: hash["uid"],
      provider: hash["provider"]
    )
  end
end

app/models/time_entry.rb
class TimeEntry < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authorizations
  has_many :time_entries

  def self.from_omniauth!(hash)
    user = create(name: hash["info"]["name"])
    user.save!
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def authenticate_user!
    unless current_user
      redirect_to "/auth/twitter"
    end
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def signed_in?
    !!current_user
  end

  helper_method :current_user, :signed_in?

  def current_user=(user)
    @current_user = user
    session[:user_id] = user.id
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @week_sum = entry_sum(week_entries)
    @month_sum = entry_sum(month_entries)
  end

  private

  def week_entries
    current_user.time_entries.where(
      date: Date.today.at_beginning_of_week..Date.today.at_end_of_week
    )
  end

  def month_entries
    current_user.time_entries.where(
      date: Date.today.at_beginning_of_month..Date.today.at_end_of_month
    )
  end

  def entry_sum(entries)
    entries.reduce(0) do |time_sum, entry|
      time_sum + entry.length
    end
  end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  def index
    if signed_in?
      redirect_to "/dashboard"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env['omniauth.auth']
    unless @auth = Authorization.find_from_hash(auth)
      # Create a new user or add an auth to existing user, depending on
      # whether there is already a user signed in.
      @auth = Authorization.create_from_hash(auth, current_user)
    end
    # Log the authorizing user in.
    self.current_user = @auth.user

    redirect_back(fallback_location: root_path)
  end

  def destroy
    if current_user
      session.delete(:user_id)
      flash[:success] = 'See you!'
    end

    redirect_to root_path
  end

  def failure;end
end

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
  before_action :set_time_entry, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /time_entries
  # GET /time_entries.json
  def index
    @time_entries = current_user.time_entries
  end

  # GET /time_entries/1
  # GET /time_entries/1.json
  def show
  end

  # GET /time_entries/new
  def new
    @time_entry = TimeEntry.new
    @time_entry.date = Date.today
  end

  # GET /time_entries/1/edit
  def edit
  end

  # POST /time_entries
  # POST /time_entries.json
  def create
    @time_entry = TimeEntry.new(time_entry_params.merge(user: current_user))

    respond_to do |format|
      if @time_entry.save
        format.html { redirect_to @time_entry, notice: 'Time entry was successfully created.' }
        format.json { render :show, status: :created, location: @time_entry }
      else
        format.html { render :new }
        format.json { render json: @time_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_entries/1
  # PATCH/PUT /time_entries/1.json
  def update
    respond_to do |format|
      if @time_entry.update(time_entry_params)
        format.html { redirect_to @time_entry, notice: 'Time entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_entry }
      else
        format.html { render :edit }
        format.json { render json: @time_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_entries/1
  # DELETE /time_entries/1.json
  def destroy
    @time_entry.destroy
    respond_to do |format|
      format.html { redirect_to time_entries_url, notice: 'Time entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_entry
      @time_entry = TimeEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_entry_params
      params.require(:time_entry).permit(:date, :length)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/_progress_card.html.slim
.card.blue-grey
  .card-content
    span.card-title= "This #{title}"
    hr
    .progressbar id=title max_value=max_value current_value=current_value = "#{number_with_precision(current_value, strip_insignificant_zeros: true)}/#{max_value}"

app/views/dashboard/index.html.slim
.container
  h1 Dashboard
  .row
    .col.s4
      = render partial: "progress_card", locals: { max_value: 20, current_value: @week_sum, title: "week" }
    .col.s4
      = render partial: "progress_card", locals: { max_value: 80, current_value: @month_sum, title: "month" }

app/views/landing_page/index.html.slim
.container
  h1 Welcome to Student Time
  p This is an app to track working hours. It has been developed with German working students in mind.
  p
    | You may contribute to the app on 
    = link_to "Github", "https://github.com/3wille/StudentTime"

app/views/layouts/application.html.slim
doctype html
html
  head
    title Student Time
    = csrf_meta_tags
    
    = stylesheet_link_tag    "application", media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag "application", 'data-turbolinks-track' => true

  body
    nav.light-blue role="navigation"
      .nav-wrapper.container
        a.brand-logo id="logo-container" href="/dashboard" Logo
        ul.right.hide-on-med-and-down
          li
            a href="/time_entries" Entries
          li
            - if signed_in?
              = link_to "Logout", sessions_path, method: :delete
            - else
              = link_to "Login" ,"/auth/twitter"
        ul.side-nav id="nav-mobile" 
         li
          a href="/time_entries" Entries
        a.button-collapse href="" data-activates="nav-mobile"
          i.material-icons.fa.fa-bars

    = yield

app/views/time_entries/_form.html.slim
.span6
  = form_for @time_entry do |f|
    - if @time_entry.errors.any?
      #error_explanation
        h2 = "#{pluralize(@time_entry.errors.count, "error")} prohibited this time_entry from being saved:"
        ul
          - @time_entry.errors.full_messages.each do |message|
            li = message

    .field
      = f.label :date
      = f.date_field :date, class: "datepicker", id: "time_entry_date"
    .field
      = f.label :length
      = f.text_field :length
    br
      .s6
        .actions
          = f.submit nil, { class: "btn waves-effect waves-light" }

app/views/time_entries/edit.html.slim
.container
  h1
   = "Editing time entry from #{@time_entry.date}"

  == render 'form'

  hr
  .s6

    = link_to 'Show', @time_entry, class: "btn waves-effect waves-teal btn-flat"
    = link_to 'Back', time_entries_path, class: "waves-effect waves-teal btn-flat"

app/views/time_entries/index.html.slim
#index-header.section
  .container
      h1.header Entries

.container
  table.striped
    thead
      tr
        th Date
        th Length
        th
        th
        th

    tbody
      - @time_entries.each do |time_entry|
        tr
          td = time_entry.date
          td = time_entry.length
          td = link_to 'Show', time_entry
          td = link_to 'Edit', edit_time_entry_path(time_entry)
          td = link_to 'Destroy', time_entry, data: { confirm: 'Are you sure?' }, method: :delete

  br

  = link_to 'New Time entry', new_time_entry_path, class: "waves-effect waves-light btn"

app/views/time_entries/new.html.slim
.container
  h1 New time_entry
  == render 'form'

  hr
  .s6
    .waves-effect.waves-teal.btn-flat
      = link_to 'Back', time_entries_path

app/views/time_entries/show.html.slim
.container
  p#notice = notice

  p
    strong Date:
    = @time_entry.date
  p
    strong Length:
    = @time_entry.length

  hr
  .s6
    .waves-effect.waves-teal.btn-flat
      = link_to 'Edit', edit_time_entry_path(@time_entry)
    .waves-effect.waves-teal.btn-flat
      = link_to 'Back', time_entries_path